#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)
#
#  OpenELEC is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  OpenELEC is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

# remove old ljalves files
echo "removing old sources ..."
rm -rf ljalves-cc
rm -rf ljalves-cc-*

################################################################################

# media_build dl
echo "getting media_build sources ..."
  if [ ! -d media_build.git ]; then
    git clone --depth=1 https://bitbucket.org/CrazyCat/media_build.git ljalves-cc/media_build
  fi

echo "cleaning media_build sources ..."
  rm -rf ljalves-cc/media_build/.git

################################################################################

# ljalves tbs drivers dl
echo "getting ljalves sources ... !!! huge !!!"
  if [ ! -d linux_media.git ]; then
    git clone --depth=1 https://github.com/crazycat69/linux_media.git -b tbs5990 ljalves-cc/media
  fi

  cd ljalves-cc/media
    git pull
    GIT_REV=`git log -n1 --pretty=format:"%ad" --date=short`

# remove unnessecary files
  rm -rf Documentation
  cd ../..

echo "copying ljalves sources ..."
  rm -rf ljalves-cc-$GIT_REV
  cp -R ljalves-cc ljalves-cc-$GIT_REV

echo "cleaning ljalves sources ..."
  rm -rf ljalves-cc-$GIT_REV/media/.git

################################################################################

echo "packing sources ..."
tar cvJf ljalves-cc-$GIT_REV.tar.xz ljalves-cc-$GIT_REV

echo "remove temporary sourcedir ..."
  rm -rf ljalves-cc-$GIT_REV
  rm -rf ljalves-cc
