#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)
#
#  OpenELEC is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  OpenELEC is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

echo "getting sources..."
  if [ ! -d linux-tbs-drivers.git ]; then
    git clone --depth=1 https://bitbucket.org/CrazyCat/linux-tbs-drivers.git
  fi

  cd linux-tbs-drivers
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf crazycat-$GIT_REV
  mv linux-tbs-drivers crazycat-$GIT_REV

echo "cleaning sources..."
  rm -rf crazycat-$GIT_REV/.git
  rm crazycat-$GIT_REV/v4l/*.o.x86
  rm crazycat-$GIT_REV/v4l/*.o.x86_r3

echo "packing sources..."
  tar cvJf crazycat-$GIT_REV.tar.xz crazycat-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf crazycat-$GIT_REV
