#!/bin/sh
################################################################################
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

echo "getting sources..."
  if [ ! -d linux-tbs-drivers.git ]; then
    git clone https://bitbucket.org/CrazyCat/linux-tbs-drivers.git
  fi

  cd linux-tbs-drivers
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf crazycat-$GIT_REV
  mv linux-tbs-drivers crazycat-$GIT_REV

echo "cleaning sources..."
  rm -rf crazycat-$GIT_REV/.git

echo "packing sources..."
  tar cvJf crazycat-$GIT_REV.tar.xz crazycat-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf crazycat-$GIT_REV
